title = "sgsa config"

[time]
tempo = 120.0
note_duration = 1.0

[adsr]
type = "AR"
attack = 0.4
decay = 0.0
sustain = 0.0
release = 0.8

[lfo]
rate = 2.0
depth = 1.0
timer = 0.33
mode = "TREMOLO"
on = false

[audio]
volume = 1.0
voicings = 16
wave_table_size = 1024
sample_rate = 48000
channels = 2

[oscilators]
oscilators = [
  { name = "saw", detune = 1.0, volume = 1.0, octave_step = 1.0, cycle = 1.0  },
  { name = "sine", detune = 1.0, volume = 1.0, octave_step = 1.0, cycle = 1.0 }
]

